#!/usr/bin/env node

const { exec, execSync} = require("child_process");
const { convertFile}  = require('convert-svg-to-png');
const fs = require("fs");
const path = require("path");

// Function to print all modules and their versions using npm ls
function printModulesAndVersions() {
  const result = execSync('npm ls --json').toString();
  const jsonResult = JSON.parse(result);
  console.log("Dependencies and their versions:");
  for (const [key, value] of Object.entries(jsonResult.dependencies)) {
    console.log(`${key}: ${value.version}`);
  }
}
printModulesAndVersions();

const svgFile = process.argv[2];
if (!svgFile) {
  throw new Error("Must specify the path to svg");
}

(async() => {
  const inputFilePath = svgFile;
  const outputFilePath = await convertFile(inputFilePath, {
    width: 480
  });
  const parsedPath = path.parse(outputFilePath);
  const outputFilePathThumb = path.join(parsedPath.dir, parsedPath.name + "-thumb.png");
  fs.rename(
    outputFilePath,
    outputFilePathThumb,
        function(err) {
          if (err) {
            console.error(`Error renaming png file`); 
          }
        }
  );

  const outputFilePath2 = await convertFile(inputFilePath, {
    scale: 3
  });

  console.log(outputFilePathThumb);
  console.log(outputFilePath2);
})();
